version: '3.8'

services:
  telegram-teacher-bot:
    build: .
    container_name: telegram-teacher-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local